### ISSUE TITLE
graphql queries

### ISSUE THREAD

**Issue by veeramarni** [swarthout/feathers-apollo#10]
I don't see you using graphql queries. Feathers is limited to only few services such as `create, setup, patch ...etc`. Don't that limit the graphql usage?

**Comment by swarthout** [comment]
While the default feathers services only have setup, patch, create, remove, etc. as events, you can easily add custom events if you need: 
https://docs.feathersjs.com/real-time/events.html#custom-events
With this, it is possible to support any graphql query or mutation.

**Comment by idibidiart** [comment]
Can you provide an example? Reduce the amount of guessing (on how to do things) that we have to do to leverage your great work? Even just a gist and link to here. Thank you. Great idea you have in Feathers + GQL integration!

**Comment by swarthout** [comment]
That is a great idea. What would you want to see? Example queries?

**Comment by idibidiart** [comment]
Awesome. I think both queries and mutations, and they could be quite arbitrary and redundant (with respect to default services), and just showing the mechanics of setting them up would be great! Thank you!!

**Comment by swarthout** [comment]
@idibidiart I added some example queries and mutations to the repo under the examples/ directory. I hope this helps

**Comment by idibidiart** [comment]
That's so helpful! Thank you.
