### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dortamiguel** [swarthout/feathers-apollo#15]
Maybe this can be integrated on this project? https://github.com/RisingStack/graffiti

**Comment by swarthout** [comment]
graffiti is a great approach to building a GraphQL server, but I think one of the main benefits of this stack is the fact that the schema is decoupled from the database implementation. Migrating this server from Mongo to any of the other [supported databases](https://docs.feathersjs.com/databases/readme.html) is trivial.

**Comment by dortamiguel** [comment]
Ok! you are right I think.
