### ISSUE TITLE
Pure "client only" version of Feathers-Apollo 

### ISSUE THREAD

**Issue by idibidiart** [swarthout/feathers-apollo#21]
I have played with this architecture. It is pretty cool, and makes a lot of sense to me, but I have been wondering why we have GraphQL sitting in the mid-tier, and why have a mid-tier at all when we can have GraphQL Anywhere (with async resolver support) sitting in the client and interacting with Feathers services running in the client that in turn wrap external resources. Why the mid tier?

**Comment by swarthout** [comment]
That is a good point and I think there is a lot of value in that approach, especially in working with existing servers. I did this in the mid tier because one of the big advantages of graphql is intuitive joins and if you are doing your joins on the client you are going to be doing a lot more network requests.

**Comment by idibidiart** [comment]
Ah! good point, yeah... but sometimes network bandwidth is cost-free (as in having an unlimited data plan or working over wifi) and the cost of operating the infrastructure is the real show stopper. I can't say that any major company would go that route but for small budget strapped projects that might be a less costly approach.

**Comment by swarthout** [comment]
True, I was thinking more about latency than server costs though. The latency of a client request is usually many times slower than a database query.

**Comment by idibidiart** [comment]
you're right, and also for security reasons... looking forward to the auk upgrade, but no pressure ! thanks again for sharing this @swarthout !!! excellent stuff.
