### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by 3kynox** [swarthout/feathers-apollo#23]
Hello there and sorry about the title ... but it's the case.

I'm learning this new technology for me and I followed the blog post here : 

https://halcyon-labs.github.io/blog/2016/07/13/eagle-has-landed/

and had a look on that one too inspired by the first one : 

https://medium.com/fuzz/the-electric-feathersjs-and-apollo-server-the-start-f338a744b34b

... and the cli started to ask me more question than exposed on the blog post, or is partially different. I managed this; but just after, the tutorial asks to call the `generate service` command where it is said to chose the generate option (which no more exists) and I have replaced by chosing "A custom service". But after it is said to edit file : 

src/services/graphql/index.js

and nothing longer here, I have a `src/services/index.js` that list the existing services and instead I have a graphql.class.js which is completely different than the showed file in tutorial (class now in it, ES2015 synthax).

I'm some kind of "blocked" now and a lot sad.

Would someone be ready to give an update to this tutorial ?

Thanks anyway.

**Comment by swarthout** [comment]
@3kynox I understand your concern. This project has not been a focus for me, and it is quite outdated at this point. I would recommend checking out the Apollo server and feathers documentation. They are both excellent and should help.
