### ISSUE TITLE
passing authorization token

### ISSUE THREAD

**Issue by jfcieslak** [swarthout/feathers-apollo#3]
how do you pass authorization token to graphql queries (like viewer query), once you are logged in? If this could be mentioned in the readme it would be awesome.

**Comment by swarthout** [comment]
That is a good question. Here is what I have been doing with the Apollo Client. When I get the token from the login mutation, I store it in local storage, so if you do the following, it should work. I'll add it to the readme and also link the blog post explanation

``` javascript
import ApolloClient, { createNetworkInterface } from 'apollo-client';

const networkInterface = createNetworkInterface('http://localhost:3030/graphql');

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    req.options.headers = {
      authorization: localStorage.getItem('feathers-jwt') ? localStorage.getItem('feathers-jwt') : null
    }
    next();
  }
}]);

const client = new ApolloClient({
  networkInterface
});
```

**Comment by psi-4ward** [comment]
I dont understand where you inject this scripts?

Currently i inject the Authorization Header via Modify-Headers Chrome Plugin

**Comment by advanwinkel** [comment]
My solution is that I pass the webtoken to Feathers from the GraphiQL screen. For that purpose I have extended the "declarations" of the RootMutation queries in Schema.js with the attribute webtoken. For instance:

```
createPost (
    post: postInput
    webtoken: String
  ): Post
```

Then in the Resolver I copy the webtoken from the args object to the context:

``` javascript
createPost(root, args, context){
          context.token = args.webtoken;
          return Posts.create(args.post, context);
```

May be not a very elegant method, but I can't think of anything else and it works.

**Comment by swarthout** [comment]
If you use this version of graphiql, you can add a header with name "Authorization" and the token as the value http://toolbox.sangria-graphql.org/graphiql

**Comment by swarthout** [comment]
Make sure to check 'proxy requests' or it will not work

**Comment by psi-4ward** [comment]
huh nice one, this should be adopted in apollos graphi
