### ISSUE TITLE
Update to new version of apollo

### ISSUE THREAD

**Issue by willmkt** [swarthout/feathers-apollo#6]
Hi, are you going to update to the new version of apollo server?

It would be cool to make a screencast and update the blog post.

thanks..

**Comment by swarthout** [comment]
I will try to update the project this weekend. Thanks for the reminder!

**Comment by willmkt** [comment]
Will you update the blog post? or make a screencast would be way more cool..

Thanks

**Comment by swarthout** [comment]
I updated the repo and the blog post to apollo-server 0.2.4
